spring.application.name=orderroom-backend

# .env を .properties 形式として読み込む（Spring Boot標準機能）
spring.config.import=optional:file:.env[.properties]

#  PostgreSQL環境設定
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hidernate設定
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
